#! /bin/sh

BASEDIR="$(dirname "$(readlink -f "$0")")"

# shellcheck source=lib/common disable=SC1091
. "$BASEDIR/lib/common"

info "Script Dir: $BASEDIR"
info "Installing..."
"$BASEDIR/install.d/remove-aur-helpers" || die "install.d/remove-aur-helpers failed"
"$BASEDIR/install.d/disable-baloo" || die "install.d/disable-baloo failed"
"$BASEDIR/install.d/harden-system" || die "install.d/harden-system failed"
"$BASEDIR/install.d/pacman-hooks" || die "install.d/pacman-hooks failed"
"$BASEDIR/install.d/configure-pacman" || die "install.d/configure-pacman failed"
"$BASEDIR/install.d/security-tools" || die "install.d/security-tools failed"
"$BASEDIR/install.d/dash" || die "install.d/dash failed"
"$BASEDIR/install.d/configure-network" || die "install.d/configure-network failed"
"$BASEDIR/install.d/harden-ssh" || die "install.d/harden-ssh failed"
"$BASEDIR/install.d/btrfs-scrub" || die "install.d/btrfs-scrub failed"
"$BASEDIR/install.d/firejail" || die "install.d/firejail failed"
"$BASEDIR/install.d/fail2ban" || die "install.d/fail2ban failed"
"$BASEDIR/install.d/enable-services" || die "install.d/enable-services failed"
"$BASEDIR/install.d/shell-prompt" || die "install.d/shell-prompt failed"
"$BASEDIR/install.d/shell-environment" || die "install.d/shell-environment failed"
"$BASEDIR/install.d/configure-flatpak" || die "install.d/configure-flatpak failed"
"$BASEDIR/install.d/git-environment" || die "install.d/git-environment failed"
"$BASEDIR/install.d/dev-scripts" || die "install.d/dev-scripts failed"
success "Done"
