#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$SCRIPTDIR")"

# shellcheck source=../lib/common disable=SC1091
. "$BASEDIR/lib/common"

install_btrfs_scrub() {
    info "Installing btrfs scrub"
    sudo cp "$BASEDIR/units/btrfs-scrub/btrfs-scrub.service" /etc/systemd/system/ || die "Failed to copy btrfs-scrub.service to /etc/systemd/system"
    sudo cp "$BASEDIR/units/btrfs-scrub/btrfs-scrub.timer" /etc/systemd/system/ || die "Failed to copy btrfs-scrub.timer to /etc/systemd/system"
    sudo systemctl daemon-reload || die "Failed to reload the systemd manager"
    sudo systemctl enable --now btrfs-scrub.timer || die "Failed to enable btrfs-scrub.timer"

    success "btrfs scrub installed"
}

install_btrfs_scrub
