#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$SCRIPTDIR")"

# shellcheck source=../lib/common disable=SC1091
. "$BASEDIR/lib/common"

disable_baloo() {
    if command -v balooctl6 >/dev/null 2>&1; then
        info "Disabling and purging baloo file indexer"
        balooctl6 disable || die "Failed to disable the baloo file indexer"
        balooctl6 purge || die "Failed to purge the baloo index"
    fi

    success "baloo disabled"
}

disable_baloo
