#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$SCRIPTDIR")"

# shellcheck source=../lib/common disable=SC1091
. "$BASEDIR/lib/common"

harden_ssh() {
    info "Hardening SSH"
    for SSHD_CONF in "$BASEDIR"/settings/sshd/*.conf; do
        SSHD_TARGET="/etc/ssh/sshd_config.d/$(basename "$SSHD_CONF")"
        sudo cp "$SSHD_CONF" "$SSHD_TARGET" || die "Failed to copy $SSHD_TARGET"
    done

    info "Installing curl for key server AuthorizedKeysCommand"
    sudo pacman -S --needed --noconfirm curl || die "Failed to install curl"

    HOSTNAME_VALUE="$(hostnamectl --static)"
    [ -n "$HOSTNAME_VALUE" ] || die "Unable to determine hostname for key server AuthorizedKeysCommand config"

    info "Rendering key server AuthorizedKeysCommand config"
    sudo tee /etc/ssh/sshd_config.d/14_KeyServer.conf > /dev/null <<EOF || die "Failed to write /etc/ssh/sshd_config.d/14_KeyServer.conf"
AuthorizedKeysCommand /usr/bin/curl -sf --connect-timeout 5 --max-time 10 https://keys.markridgwell.com/keys/$HOSTNAME_VALUE/%u
AuthorizedKeysCommandUser nobody
EOF

    success "SSH hardened"
}

harden_ssh
