#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$SCRIPTDIR")"

# shellcheck source=../lib/common disable=SC1091
. "$BASEDIR/lib/common"

remove_aur_helpers() {
    info "Removing AUR helpers"
    if pacman -Qq yay 2>/dev/null; then
        sudo pacman -Rns --noconfirm yay || die "Failed to remove yay"
    fi
    if pacman -Qq paru 2>/dev/null; then
        sudo pacman -Rns --noconfirm paru || die "Failed to remove paru"
    fi

    success "AUR helpers removed"
}

remove_aur_helpers
