#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$(dirname "$(dirname "$SCRIPTDIR")")")"

# shellcheck source=../../../lib/common disable=SC1091
. "$BASEDIR/lib/common"

if [ ! -f "$HOME/dotnet-tools.json" ]; then

  cd "$HOME" && dotnet new tool-manifest

fi

[ -f "$HOME/dotnet-tools.json" ] || die "No tool manifest"


TOOLS="sleet \
       TSQLLint \
       FunFair.BuildCheck \
       FunFair.BuildVersion \
       Credfeto.Changelog.Cmd \
       Credfeto.Package.Push \
       Credfeto.Package.Update \
       Credfeto.DotNet.Code.Analysis.Overrides.Cmd \
       Credfeto.DotNet.Repo.Tools.Cmd \
       Credfeto.DotNet.Repo.Formatter \
       FunFair.Content.Packager.Cmd \
       FunFair.Content.PackageSigner.Cmd \
       JetBrains.ReSharper.GlobalTools \
       powershell \
       dotnet-script \
       dotnet-reportgenerator-globaltool \
       csharpier \
       ilspycmd"

for TOOL in $TOOLS; do
   info "Installing $TOOL"
   dotnet tool install --local "$TOOL"
done

success "Done"
