#!/bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$(dirname "$(dirname "$SCRIPTDIR")")")"

# shellcheck source=../../../lib/common disable=SC1091
. "$BASEDIR/lib/common"

RELEASE=$1

[ -z "$RELEASE" ] && die "Invalid release"

GIT_ROOT=$(git rev-parse --show-toplevel) || die "Not in a git repository"
CHANGELOG=$GIT_ROOT/CHANGELOG.md

[ -f "$CHANGELOG" ] || die "CHANGELOG.md not found in repository"

dotnet changelog -c "$RELEASE" || die "Failed to update changelog"
git add "$CHANGELOG" || die "Failed to stage $CHANGELOG"
git commit "$CHANGELOG" -m"Changelog for $RELEASE" -n || die "Failed to commit changelog"
git push --no-verify || die "Failed to push"
success "Released $RELEASE"
