#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$(dirname "$(dirname "$SCRIPTDIR")")")"

# shellcheck source=../../../lib/common disable=SC1091
. "$BASEDIR/lib/common"

STREAMER=$1
[ -z "$STREAMER" ] && die "Streamer not specified"

while true
do
  streamlink --player=mpv "https://twitch.tv/$STREAMER" best > /dev/null 2>&1
  sleep 60
done
