#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$(dirname "$(dirname "$SCRIPTDIR")")")"

# shellcheck source=../../../lib/common disable=SC1091
. "$BASEDIR/lib/common"

PACKAGES="com.brave.Browser \
          org.mozilla.firefox \
          com.opera.Opera \
          com.discordapp.Discord \
          com.spotify.Client \
          com.todoist.Todoist \
          com.bitwarden.desktop \
          org.mozilla.Thunderbird \
          com.github.iwalton3.jellyfin-media-player \
          com.ktechpit.whatsie"

for PACKAGE in $PACKAGES; do
  info "Installing ${PACKAGE}..."
  flatpak install -y "$PACKAGE"
done

success "All flatpak packages installed"
