#! /bin/sh

SCRIPTDIR="$(dirname "$(readlink -f "$0")")"
BASEDIR="$(dirname "$(dirname "$(dirname "$SCRIPTDIR")")")"

# shellcheck source=../../../lib/common disable=SC1091
. "$BASEDIR/lib/common"

[ -z "$DOTNET_PREVIEW_VERSION" ] && die "DOTNET_PREVIEW_VERSION not defined"

BRANCH="depends/sdk/dotnet/$DOTNET_PREVIEW_VERSION/preview"

info "Using Branch: $BRANCH"

git fetch && git checkout main && git pull && git checkout -b "$BRANCH" && update-dotnet-sdk && success "Branch $BRANCH initialised"
